---
title: "Gov 50 Final Project"
author: "Kareem Fahs"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

  Do American citizens vote less in presidential elections during times of economic success and more in times of economic decline? In this study, I plan to examine the correlation between voter turnout and GDP in presidential election years. I hypothesize that in times of economic decline, citizens will be more likely to vote in an effort to drive change in economic policy. Concurrently, I believe that in times of relative economic prosperity voters will experience a sense of security and maybe not be as motivated to go to the polls. I would combine two separate data sets for this study: one on the turnout results of every state in every presidential election since 1976, and the other on the GDP of the U.S. in every year from 1960-2023. The explanatory variables would be the yearly GDP and GDP per capita of the U.S, with the outcome variable being the turnout in presidential elections since 1976. If we see a correlation in which turnout (X) is typically higher when GDP (Y) is low, that would support my hypothesis that low economic strength leads to the electorate opting for change. If instead, the data reflects relatively steady turnout rates that are not affected by GDP that may contribute to disproving my hypothesis. Another thing that could disprove my hypothesis is if we actually find that turnout is higher during times of economic strength; this could be explained by the electorate being motivated to protect the strength of the economy leading to higher turnout. 
